+define+CLOCK_PERIOD=10ns
$ALUVM_HOME/sim/UVM_pkg.sv
$ALUVM_HOME/common/alu_assertions.sv
$ALUVM_HOME/common/alu_interface.sv
$ALUVM_HOME/common/alu_trans.sv
$ALUVM_HOME/env_comp/driver/alu_driver.sv
$ALUVM_HOME/env_comp/driver/alu_sequencer.sv
$ALUVM_HOME/env_comp/monitor/alu_monitor.sv
$ALUVM_HOME/env_comp/monitor/alu_coverage.sv
$ALUVM_HOME/env_comp/scoreboard/alu_scoreboard.sv
$ALUVM_HOME/sequences/alu_sequences.sv
$ALUVM_HOME/common/alu_env.sv
$ALUVM_HOME/tests/alu_tests.sv
$ALUVM_HOME/sim/user_files/alu8.sv
$ALUVM_HOME/sim/ALUVM_top.sv